ARG NODE_VERSION=21.7.3
# ARG ALPINE_VERSION=3.17.2

FROM node:${NODE_VERSION}-alpine AS node

# https://github.com/alpinelinux/docker-alpine/issues/396
FROM oven/bun:alpine

# FROM alpine:${ALPINE_VERSION}

RUN apk add -u aws-cli

# https://stackoverflow.com/a/76132347
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

# COPY --from=bun /usr/local/bin /usr/local/bin

# RUN node -v
# RUN aws --version
# RUN bun -v


# https://github.com/sst/ion/issues/45
# ENV NO_BUN=true 